//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Paciente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int ID_Paciente { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Idade { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string Genero { get; set; }
        public string Doencas { get; set; }
        public string Alergias { get; set; }
        public string Telefone { get; set; }
        public string Contato { get; set; }
        public string Logradouro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
    }
}
